import { Box, Container, Grid } from '@mui/material'
import { GetServerSideProps, InferGetServerSidePropsType } from 'next'
import Head from 'next/head'
import Product from '../components/Product'
import { ProductProps } from '../types/Product.types'

const Home = ({ products }: InferGetServerSidePropsType<typeof getServerSideProps>) => {

  return (
    <Box py={4} component='main' >
      <Head>
        <title>Shopping App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Grid container spacing={2} >
          {products.map((product: ProductProps) => {
            return <Grid key={product.id} item xs={12} sm={6} lg={4} zeroMinWidth> <Product product={product} /></Grid>
          })}
        </Grid>
      </Container>
    </Box>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async () => {
  const response = await fetch("https://fakestoreapi.com/products")
  const data = await response.json()

  return {
    props: {
      products: data
    }
  }
}
